# Profile PROD

# ===============================
# Datasource configuration
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# Jwt
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# ===============================
# Swagger / OpenAPI
# ===============================
springdoc.swagger-ui.enabled=${SWAGGER_ENABLED:false}
springdoc.api-docs.enabled=${SWAGGER_ENABLED:false}
springdoc.swagger-ui.path=/swagger-ui.html

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# ===============================
# Media storage path
# ===============================
media.storage.path=/uploads/media

# ===============================
# Logs
# ===============================
logging.level.root=INFO